<!DOCTYPE labwork [
  <!ELEMENT labwork -- (title?, task+, info*)>
  <!ELEMENT title -- (subject?, group?, lab_number?, lab_title?)>
  <!ELEMENT subject -- (#PCDATA)>
  <!ELEMENT group -- (#PCDATA)>
  <!ELEMENT lab_number -- (#PCDATA)>
  <!ELEMENT lab_title -- (#PCDATA)>
  <!ELEMENT task -- (task_number?, task_description?)>
  <!ELEMENT task_number -- (#PCDATA)>
  <!ELEMENT task_description -- (#PCDATA)>
  <!ELEMENT info -- (resource*)>
  <!ELEMENT resource -O (#PCDATA)>
  <!ELEMENT link -- (#PCDATA)>
  <!ATTLIST link href CDATA #REQUIRED>
]>

<labwork>
  <title>
    <subject>Базовые информационные технологии и процессы</subject>
    <lab_number>Лабораторная работа №5</lab_number>
    <group>гр. 402-422</group>
    <lab_title>Языки разметки</lab_title>
  </title>

<task>
   <task_description>
      Просмотреть в материалах темы «Языки разметки» презентацию о Разметке Текстов.
    </task_description>
  </task>

  <task>
    <task_number>1</task_number>
    <task_description>
      Разметить список объектов, имеющих отношение к выбранной вами предметной области (фамилии клиентов, адреса филиалов, фамилии работников и т.п.) на языке HTMLв рамках набора элементов из документа «Кратко об HTML». В случае затруднений с поиском материала разметить список группы. Число позиций списка не менее 10, в каждом не менее 2 элементов вложенного списка. В отчет поместить размеченный текст с указанием назначения каждого элемента. Лучше всего и желательно разметку делать в текстовом редакторе. Если будете делать в специализированном программном продукте, то придется описывать назначение элементов, которые для непосредственно разметки списка могут быть и не нужны.
    </task_description>
  </task>

  <task>
    <task_number>2</task_number>
    <task_description>
      Разметить таблицу с данными, относящимися к вашей предметной области (например, перечень блюд с их стоимостью и весом, перечень работников или клиентов с телефонами и окладом и т.п.). В таблице не менее 10 строк и 4 столбцов. В случае затруднений с данными предметной области разметить одну из таблиц, приведенных в задании. Постараться получить максимально точное внешнее представление при интерпретации разметки таблицы в браузере. В отчет поместить размеченный текст с указанием назначения каждого элемента.
    </task_description>
  </task>

  <task>
    <task_number>3</task_number>
    <task_description>
      Просмотреть в материалах темы «Языки разметки» презентацию о Разметке Текстов. Обратить внимание на правила построения DTD.
      Проанализируйте текст задания на данную лабораторную как документ типа «Задание на лабораторную». Исходя из возможных задач обработки текстов данного типа разработайте DTD языка разметки (ML) документов LWML (Laboratory Work Markup Language). Проведите разметку данного задания как пример разметки на сконструированном вами ML. В отчет поместить описание DTD Вашего ML, описание ограничений на структуру данного типа документов и текст разметки данного задания.
    </task_description>
  </task>
  
  <task>
    <task_description>
      Разместить итоговый файл, включающий размеченный список, таблицу, описание DTD Вашего языка разметки и пример разметки в соответствующем разделе электронного журнала.
    </task_description>
  </task>

  <info>
    <resource>
      	Если есть необходимость вспомнить элементы HTML можно воспользоваться, например, ресурсом <link href= “http://www.webremeslo.ru/html/glava1.html”>http://www.webremeslo.ru/html/glava1.html</link> или описанием в материалах к лабораторной.
  </info>

</labwork>
